version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DOCKER_DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"
    environment:
      - ETCD_ROOT_PASSWORD=${ETCD_ROOT_PASSWORD}
    restart: always
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "ETCDCTL_API=3 etcdctl --user=root:${ETCD_ROOT_PASSWORD} --endpoints=http://localhost:2379 endpoint health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    restart: always
    privileged: true
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - TZ=Asia/Shanghai
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ${DOCKER_DATA_PATH}/clickhouse/data:/var/lib/clickhouse
      - ${DOCKER_DATA_PATH}/clickhouse/logs:/var/log/clickhouse-server
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    depends_on:
      - clickhouse
    volumes:
      - ${DOCKER_DATA_PATH}/grafana:/var/lib/grafana
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:3000/api/health | grep -q 'ok'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gopeck-admin:
    container_name: gopeck-admin
    build:
      context: ..
      dockerfile: deploy/Dockerfile-admin
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      - DB_ADDR=mysql:3306
      - REDIS_ADDR=redis:6379
      - ETCD_ADDR=etcd:2379
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_healthy
      redis:
        condition: service_healthy

  gopeck-integrator:
    container_name: gopeck-integrator
    build:
      context: ..
      dockerfile: deploy/Dockerfile-integrator
    ports:
      - "8082:8082"
    networks:
      - backend
    environment:
      - DB_ADDR=mysql:3306
      - REDIS_ADDR=redis:6379
      - ETCD_ADDR=etcd:2379
      - CLICKHOUSE_ADDR=clickhouse:9000
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  gopeck-pecker:
    container_name: gopeck-pecker
    build:
      context: ..
      dockerfile: deploy/Dockerfile-pecker
    ports:
      - "8083:8083"
    networks:
      - backend
    environment:
      - REDIS_ADDR=redis:6379
      - ETCD_ADDR=etcd:2379
    depends_on:
      etcd:
        condition: service_healthy
      redis:
        condition: service_healthy

  gopeck-ui:
    container_name: gopeck-ui
    build:
      context: ..
      dockerfile: deploy/Dockerfile-ui
    ports:
      - "8080:9211"
    networks:
      - backend
    depends_on:
      - gopeck-admin
      - gopeck-integrator
      - gopeck-pecker

networks:
  backend:
