// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: api/integrator/v1/integrate.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId           uint64  `protobuf:"varint,1,opt,name=planId,proto3" json:"planId,omitempty"`
	StressTime       int32   `protobuf:"varint,2,opt,name=stressTime,proto3" json:"stressTime,omitempty"`
	IntervalLen      int32   `protobuf:"varint,3,opt,name=intervalLen,proto3" json:"intervalLen,omitempty"`
	StressType       int32   `protobuf:"varint,4,opt,name=stressType,proto3" json:"stressType,omitempty"`
	StressMode       int32   `protobuf:"varint,5,opt,name=stressMode,proto3" json:"stressMode,omitempty"`
	StartTime        int64   `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	StepIntervalTime int32   `protobuf:"varint,7,opt,name=stepIntervalTime,proto3" json:"stepIntervalTime,omitempty"`
	UserId           string  `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	Tasks            []*Task `protobuf:"bytes,9,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *IntegrateRequest) Reset() {
	*x = IntegrateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_integrator_v1_integrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntegrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrateRequest) ProtoMessage() {}

func (x *IntegrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_integrator_v1_integrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrateRequest.ProtoReflect.Descriptor instead.
func (*IntegrateRequest) Descriptor() ([]byte, []int) {
	return file_api_integrator_v1_integrate_proto_rawDescGZIP(), []int{0}
}

func (x *IntegrateRequest) GetPlanId() uint64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *IntegrateRequest) GetStressTime() int32 {
	if x != nil {
		return x.StressTime
	}
	return 0
}

func (x *IntegrateRequest) GetIntervalLen() int32 {
	if x != nil {
		return x.IntervalLen
	}
	return 0
}

func (x *IntegrateRequest) GetStressType() int32 {
	if x != nil {
		return x.StressType
	}
	return 0
}

func (x *IntegrateRequest) GetStressMode() int32 {
	if x != nil {
		return x.StressMode
	}
	return 0
}

func (x *IntegrateRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *IntegrateRequest) GetStepIntervalTime() int32 {
	if x != nil {
		return x.StepIntervalTime
	}
	return 0
}

func (x *IntegrateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntegrateRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId               uint64 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Url                  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	RequestContentLength int32  `protobuf:"varint,3,opt,name=requestContentLength,proto3" json:"requestContentLength,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_integrator_v1_integrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_integrator_v1_integrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_integrator_v1_integrate_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Task) GetRequestContentLength() int32 {
	if x != nil {
		return x.RequestContentLength
	}
	return 0
}

type IntegrateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *IntegrateReply) Reset() {
	*x = IntegrateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_integrator_v1_integrate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntegrateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrateReply) ProtoMessage() {}

func (x *IntegrateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_integrator_v1_integrate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrateReply.ProtoReflect.Descriptor instead.
func (*IntegrateReply) Descriptor() ([]byte, []int) {
	return file_api_integrator_v1_integrate_proto_rawDescGZIP(), []int{2}
}

func (x *IntegrateReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_api_integrator_v1_integrate_proto protoreflect.FileDescriptor

var file_api_integrator_v1_integrate_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x22, 0xb5,
	0x02, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73,
	0x74, 0x65, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x74, 0x65, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x64, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x32, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x24, 0x0a, 0x0e,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0x57, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x16, 0x5a, 0x14, 0x61,
	0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_integrator_v1_integrate_proto_rawDescOnce sync.Once
	file_api_integrator_v1_integrate_proto_rawDescData = file_api_integrator_v1_integrate_proto_rawDesc
)

func file_api_integrator_v1_integrate_proto_rawDescGZIP() []byte {
	file_api_integrator_v1_integrate_proto_rawDescOnce.Do(func() {
		file_api_integrator_v1_integrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_integrator_v1_integrate_proto_rawDescData)
	})
	return file_api_integrator_v1_integrate_proto_rawDescData
}

var file_api_integrator_v1_integrate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_integrator_v1_integrate_proto_goTypes = []interface{}{
	(*IntegrateRequest)(nil), // 0: integrate.IntegrateRequest
	(*Task)(nil),             // 1: integrate.Task
	(*IntegrateReply)(nil),   // 2: integrate.IntegrateReply
}
var file_api_integrator_v1_integrate_proto_depIdxs = []int32{
	1, // 0: integrate.IntegrateRequest.tasks:type_name -> integrate.Task
	0, // 1: integrate.IntegrateService.integrate:input_type -> integrate.IntegrateRequest
	2, // 2: integrate.IntegrateService.integrate:output_type -> integrate.IntegrateReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_integrator_v1_integrate_proto_init() }
func file_api_integrator_v1_integrate_proto_init() {
	if File_api_integrator_v1_integrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_integrator_v1_integrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntegrateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_integrator_v1_integrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_integrator_v1_integrate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntegrateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_integrator_v1_integrate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_integrator_v1_integrate_proto_goTypes,
		DependencyIndexes: file_api_integrator_v1_integrate_proto_depIdxs,
		MessageInfos:      file_api_integrator_v1_integrate_proto_msgTypes,
	}.Build()
	File_api_integrator_v1_integrate_proto = out.File
	file_api_integrator_v1_integrate_proto_rawDesc = nil
	file_api_integrator_v1_integrate_proto_goTypes = nil
	file_api_integrator_v1_integrate_proto_depIdxs = nil
}
